---
- name: Configure and Create a LUKS Disk

  hosts: clevis
  vars:
    disk: /dev/vdb
    luks_pw: redhatRHT
  tasks:

# Create Partition on Disk
    - name: Partition Disk {{ disk }}
      parted:
        device: "{{ disk }}"
        state: present
        number: 1

# LuksFormat Disk
    - name: Create a LUKS Formatted Partition
      shell: echo -n "{{ luks_pw }}" | cryptsetup luksFormat /dev/vdb1 -

# Get LUKS Key and Metadata
    - name: Dump LUKS Formatted Partition Information
      shell: cryptsetup luksDump /dev/vdb1
